---
version: "3.3"
# v1.5
# updated: 2022/10/29

services:

  organizr:
    image: ghcr.io/organizr/organizr
    container_name: organizr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/organizr:/config
    ports:
      - 9983:80
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget:arm32v7-latest
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/nzbget:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:arm32v7-latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/radarr:/config
      - ${FILES}/movies:/movies
      - ${DOWNLOADS}:/downloads
    ports:
      - 37878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:arm32v7-latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${APPDATA}/sonarr:/config
      - ${FILES}/tv:/tv
      - ${DOWNLOADS}:/downloads
    ports:
      - 38989:8989
    restart: unless-stopped

  nzbhydra2:
    image: linuxserver/nzbhydra2:arm32v7-latest
    container_name: nzbhydra2
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/nzbhydra2:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 35076:5076
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns:arm32v7-latest
    container_name: duckdns
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${DDNSDOMAIN}
      - TOKEN=${DDNSTOKEN}
      - LOG_FILE=true #optional
    volumes:
      - ${APPDATA}:/config #optional
    restart: unless-stopped

  cloudcmd:
    image: joeychen/rpi-cloudcmd:latest
    container_name: cloudcmd
    volumes:
      - ~:/srv
      - /:/mnt/fs_omv
      - /srv:/OMV_drives 
    ports:
      - 48000:8000
    restart: unless-stopped    

#  doublecommander:
#    image: linuxserver/doublecommander:latest
#    container_name: doublecommander
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ${APPDATA}/doublecommander:/config
#      - /srv:/OMV_drives
#    ports:
#      - 3000:3000
#    restart: unless-stopped

